### ISSUE TITLE
Creating overlay for fullscreen dx11 game

### ISSUE THREAD

**Issue by easly1989** [coltonon/Charm#2]
Hello there!
I'm trying to make an overlay for FFXIV.

I just want to show a message (a rectangular box with some text in it).

I managed to draw over the game when it is windowed,
is it possible to use your library to draw something even when the game is in fullscreen mode?

**Comment by coltonon** [comment]
Fullscreen mode it's not possible to overlay a window on top of.  You'll have to do a dx11 hook or similar.
