### ISSUE TITLE
Charm for .NET 3.5

### ISSUE THREAD

**Issue by GazziFX** [coltonon/Charm#4]
I want to use in .NET 3.5 assembly but its not allowed to use.
Can I use UnityEngine Vectors and Matrix?
My test solution https://github.com/GazziFX/Charm-NET-3.5

**Comment by coltonon** [comment]
I'm not extremely familiar with .NET versions below 4, but you should be able to pass your vector to the template function fine.  Any luck?

**Comment by GazziFX** [comment]
I gave up cause BattlEye block load of charm native dll

**Comment by coltonon** [comment]
Well yeah you're not going to be able to use ReadProcessMemory (or _OpenProcess_ to be exact, to get a handle to the game) with a Kernel level anti-cheat present.  There's a reason public cheats aren't very common on those games, that being they're not easy to write.
